version: '3.1'

volumes:
  data-db:
  init-db:
  
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    volumes:
      - ./data-db:/data/db
      - ./init-db:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: django_app_database
    ports:
      - 27017:27017
    networks:
      - compose-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: mongodb
    links:
        - mongodb
    networks:
        - compose-network
  
  web:
    build: .
    container_name: web
    image: app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/django_mongodb_docker
    ports:
      - "8000:8000"
    depends_on:
      - migration
    links:
      - mongodb

  migration:
    build: .
    image: app
    command: python manage.py migrate
    volumes:
      - .:/django_mongodb_docker
    links:
      - mongodb
    depends_on:
      - make_migrations
    networks:
      - compose-network

  make_migrations:
    build: .
    image: app
    command: python manage.py makemigrations
    volumes:
      - .:/django_mongodb_docker
    links:
      - mongodb
    depends_on:
      - mongodb
    networks:
      - compose-network
networks: 
  compose-network:
    driver: bridge
      



